name:                opengl-sandbox
version:             0.1.0.0
github:              "githubuser/opengl-sandbox"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- app/cube.vert
- app/cube.frag
- app/lamp.vert
- app/lamp.frag

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/opengl-sandbox#readme>

dependencies:
- base >= 4.7 && < 5
- OpenGL
- bytestring
- containers
- lens
- linear
- mtl
- sdl2
- vector

default-extensions:
  - RecordWildCards

library:
  source-dirs: src
  ghc-options:
    - -Wunused-imports

executables:
  opengl-sandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wunused-imports
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengl-sandbox

tests:
  opengl-sandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengl-sandbox
